<a href="https://colab.research.google.com/github/abhi4143/deep_learning/blob/Assessment---1/Assessment_1_question_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
#20MAI0005 
#ABHISHEK_KUMAR
#Creating Input matrix
import numpy as np


In [43]:

values = ([2,3],[5,6],[8,9])
print("Training input values without Bias\n", values)


Training input values without Bias
 ([2, 3], [5, 6], [8, 9])


In [44]:
#Adding Bias to the input values
test2 = [[-1]] * len(values)
values = np.concatenate((test2, values), axis = 1)  
print("Training input values with bias in it\n",values)


Training input values with bias in it
 [[-1  2  3]
 [-1  5  6]
 [-1  8  9]]


In [45]:
#Creating random weights
m=3     #number of elements in each row of inputs
n=1 
weights = np.random.rand(m,n)*0.1 - 0.5
print("Initial random weights\n",weights)


Initial random weights
 [[-0.47748839]
 [-0.46242498]
 [-0.44925722]]


In [46]:

#Target values Matrix
final = ([0],[1],[1])
print("Training data target values are\n", final)


Training data target values are
 ([0], [1], [1])


In [47]:
#Method for updating weights
def updateWeights(weights, inputs, activation, targets):
    eta = 0.25
    weights += eta*np.dot(np.transpose(inputs), targets - activation)
    return weights


In [48]:
#Creating Methods for Learning
def  prediction (inputs, weights, targets):
    #representing Activation function with 'ack [[]]' variable
    ack = [[0]] * len(inputs)
    for i in range(0, len(inputs)):    
        for j in range(0,len(weights)):
            ack[i] += inputs[i][j] * weights[j]
        ack[i] = np.where(ack[i]>0, 1, 0)
        #checking values with target
        if(targets[i] != ack[i]):
            weights = updateWeights(weights, inputs, ack[i], targets)
        print(ack[i])
    return weights


In [49]:
#Training our model and extracting stable weights
iterations = 5
for temp in range(0, iterations):
    print("\nIteration ",temp+1,"\n")
    weights = prediction(values, weights, final)
    
print("\nTrained Weights\n", weights)



Iteration  1 

[0]
[0]
[1]

Iteration  2 

[1]
[1]
[1]

Iteration  3 

[1]
[1]
[1]

Iteration  4 

[1]
[1]
[1]

Iteration  5 

[1]
[1]
[1]

Trained Weights
 [[0.02251161]
 [0.78757502]
 [0.30074278]]


In [53]:
#Testing our own data
def perceptronPredict(weights, newInput):
    ac = np.dot(newInput, weights)
    ac = np.where(ac>0, 1, 0)
    print(ac)


newInput = ([-1.0, 7, 8])
perceptronPredict(weights, newInput)

[1]


https://github.com/abhi4143/deep_learning/tree/Assessment---1




